### ISSUE TITLE
Plugins not showing up in HBCommander

### ISSUE THREAD

**Issue by ghost** [alkresin/hbedit#2]
Hi,

While in the commander, F11 doesn't show anything.

I tried copying some of the plugins in hbc.ini to the HBEdit.exe directory, but they still don't show up.

I also tried specifying the full path of the plugins in the hbc.ini file.

I tried checking the length of the  folder at the console prompt, and it shows zero.

=Qout(Len(FilePane():aPlugins)
0
NIL

In contrast, the aDefPaths array properly displays 12 paths from the hbc.ini file.

=Qout(Len(FilePane():aDefPaths)

12
Nil

Edit:  I also tried adding a single plugin array manually at the console, then confirming it was added properly.  But F11 still returns nothing.

=AADD( FilePane():aPlugins, { "plug_hbc_latin.hrb", "Convert", "Convert file name" } )

=QOut( Len( FilePane():aPlugins) )

(returns 1)

=QOut( Len( FilePane():aPlugins[1]) )

(returns 3)

**Comment by alkresin** [comment]
Hm...
 It looks like the section name in hbc.ini isn't [PLUGINS] - maybe, some typo...

To add it manually, try:
=AADD( FilePane():aPlugins, { "plug_hbc_latin.hrb", "Convert file name", "", Nil, Nil } )
the format of aPlugins array isn't the same as in ini file.

BTW, there is no need to use QOut() in expressions - results are stringified with hb_ValToExp()

**Comment by ghost** [comment]
The manual intervention worked.  F11 displayed the Conversion plugin.

**Comment by alkresin** [comment]
As I understand, without it the list of plugins is absent?
Check:
  =edi_FindPath( "plugins" + hb_ps() + "plug_hbc_latin.hrb" )
It should return the full path to this hrb file.

**Comment by ghost** [comment]
That's correct.  Without populating the aPlugins array manually, it's empty.  If we do F11, nothing shows up.


This morning, I copied all of the  .hrb plugins file to the same folder as HBEdit.  After running HBEdit, F11 still shows nothing.

=edi_FindPath( "plugins" + hb_ps() + "plug_hbc_latin.hrb" ) returns 
   
  Nil.


The other day, I typed the full path of the .hrb files in the hbc.ini file.  F11 also showed nothing.

**Comment by alkresin** [comment]
The problem is in return value of edi_FindPath().
   IF File( cFullPath := ( edi_CurrPath() + cFile ) ) .OR. File( cFullPath := ( hb_DirBase() + cFile ) )
      RETURN cFullPath
   ENDIF

If the _plug_hbc_latin.hrb_ is in _plugins_ directory, which is in the same directory where hbedit.exe is placed ( hb_DirBase() ), the second File() call must return .T. and the function must return the full path.

**Comment by ghost** [comment]
That did the trick, thanks.

I created a plugins subfolder within the c:\HbEdit folder, and all of the plugins in hbedit.ini and hbc.ini show up with F11, in the Editor and the Commander.

All set, thanks Kresin.
